# -*- coding: utf-8 -*-
"""inheitance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxRqzWXs0JPyDWG4hkFf0eH8ceQpKs2O

**Inheritance**

There are a 5 types of inheritance

1  -->  single level inheritance

2 --->  multi - level inheritance

3  -->  multiple  inheritance

4  ---> hierarchical inheritance

5 ---> hybrid  inheritance
"""

# single level inheritance
class animal:
  def eat(self):
    print("eat")
class dog(animal):
  def bark(self):
    print("bark")

d = dog()
d.bark()
d.eat()

class clg:
    def cse(self):
        print("--- CSE dept ---")
    def cse_A(self):
        print("CSE_A Students")

    def cse_B(self):
        print("CSE_B Students")

class ece(clg):
    def ece_dept(self):
        print("--- ECE dept ---")

    def ece_A(self):
        print("ECE_A Students")

    def ece_B(self):
        print("ECE_B Students")


c = clg()
c.cse()
c.cse_A()
c.cse_B()


e = ece()
e.ece_dept()
e.ece_A()
e.ece_B()

"""**multi - level inheritance**

Syntax:

class class1:

     <function>

class class2(class1):

     <function>

class class3(class2):

      <function>

      
      '
      
      '
      
      '
      
      '
      
      '
      
class classn(class n-1):

      <function>
"""

class Animal():
  def Speak(self):
    print("Speak")

  def sleep(self):
    print("sleep")

class Dog(Animal):
  def bark(self):
    print("Bark")
class dogchild(Dog):
  def eat(self):
    print("eat")

d = dogchild()
d.Speak()
d.sleep()
d.bark()
d.eat()

"""**Multiple Inheritance**

Multiple Inheritance allows a child class to inherit features (methods and attributes) from more than one parent class. This is powerful but can be complex, as Python needs a specific set of rules to decide which parent's features to use if there are conflicts.

class Base1:

    def method_1(self):

        print("From Base 1")

class Base2:

    def method_2(self):

        print("From Base 2")


class Derived(Base1, Base2):

    pass
"""

class Calculation1():
  def sum(self,a,b):
    return a + b
class Calculation2():

  def sub(self,a,b):
    return a - b
class Calculation3():
  def mul(self,a,b):
    return a * b
class Calculation4():
  def div(self,a,b):
    return a / b
class divided(Calculation1,Calculation2,Calculation3,Calculation4):
  def div(self,a,b):
    return a / b
d = divided()
print(d.sum(10,20))
print(d.sub(10,20))
print(d.mul(10,20))
print(d.div(10,20))

"""**hierarchical inheritance**

Hierarchical Inheritance in Python occurs when one parent class is inherited by multiple child classes.

It works like a real-world family tree: a parent can have multiple children. Each child shares the parent's traits (methods/attributes) but also has its own unique traits. The children, however, do not share traits with each other directly.

Syntax:

class ParentClass:

    # Parent body

    pass


class ChildClass1(ParentClass):

    # Child 1 body

    pass


class ChildClass2(ParentClass):

    # Child 2 body

    pass
"""

class Brands:
    def brand_name(self):
        print("Brand Name: Apple")


class iPhone(Brands):
    def model(self):
        print("Model: iPhone 15 Pro")


class iPad(Brands):
    def model(self):
        print("Model: iPad Air")


class MacBook(Brands):
    def model(self):
        print("Model: MacBook Pro")



p1 = iPhone()
p1.brand_name()
p1.model()
p2 = iPad()
p2.brand_name()
p2.model()

"""**hybrid Inheritance**

Hybrid Inheritance in Python is a combination of two or more types of inheritance within the same program.

It is not a specific "type" on its own, but rather a structure where you mix Single, Multiple, Multilevel, or Hierarchical inheritance together.
"""

class School:
    def school_func(self):
        print("This function is in School.")

class Student1(School):
    def func1(self):
        print("This function is in Student 1.")

class Student2(School):
    def func2(self):
        print("This function is in Student 2.")

#Multiple Inheritance (Student3 inherits from both Student1 and Student2)
class Student3(Student1, Student2):
    def func3(self):
        print("This function is in Student 3.")


obj = Student3()
obj.func1()        # From Student1
obj.func2()        # From Student2
obj.school_func()  # From School (Grandparent)